### ISSUE TITLE
Platzi x New Relic x GitHub Education Challenge Results

### ISSUE THREAD

**Issue by VirtualHorror** [gittogethers/platzi#2]
Hi @ritarenee15 @AndreaGriffiths11 @morganersery1,

I participated in the Platzi x New Relic x GitHub Education challenge to modernize the Platzi Food Delivery app. The announcement of the winners and prizes was scheduled for the 15th, but today is the 19th and there hasn't been any update.

Could you please provide an update on when the winners will be announced?

Thanks!

**Comment by morganersery1** [comment]
@VirtualHorror There are a few additional items we've asked of the participants. We're currently going through all submissions and evaluating. Winners will be announced by the end of next week on the repo, in social and on the Platzi blog.
